timeout: '3000s'
images:
  - 'gcr.io/$PROJECT_ID/instana-agent-docker:$BRANCH_NAME-$COMMIT_SHA-dynamic-$_ARCH'
  - 'gcr.io/$PROJECT_ID/instana-agent-docker:$BRANCH_NAME-$COMMIT_SHA-static-$_ARCH'

substitutions:
  _FLAVOR: dynamic
  _ARCH: x86_64

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'mkdir -p /run/secrets && gcloud secrets versions access latest --secret=instana-qa-instana-agent-docker-prs > download_key'
  - name: 'docker'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        DOCKER_BUILDKIT=1 docker build dynamic/ --no-cache --build-arg arch=$_ARCH --secret id=download_key,src=download_key --label "version=${releaseVersion}" -t gcr.io/$PROJECT_ID/instana-agent-docker:$BRANCH_NAME-$COMMIT_SHA-dynamic-$_ARCH
  - name: 'docker'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        DOCKER_BUILDKIT=1 docker build static/ --no-cache --build-arg arch=$_ARCH --secret id=download_key,src=download_key --label "version=${releaseVersion}" -t gcr.io/$PROJECT_ID/instana-agent-docker:$BRANCH_NAME-$COMMIT_SHA-static-$_ARCH
