resources:
  - name: instana-agent-docker-git
    type: git
    icon: github
    source:
      uri: https://github.com/instana/instana-agent-docker.git
      branch: ((branch))
      ignore_paths:
        - README.md

jobs:
  - name: s390x-build
    max_in_flight: 1
    public: true
    plan:
      - get: instana-agent-docker-git
        trigger: true
      - task: build-s390x-dynamic
        privileged: true # required by the concourse-oci-build-task
        file: instana-agent-docker-git/ci/build-any-arch-docker-image-task.yml
        input_mapping:
          source: instana-agent-docker-git
        vars:
          docker-context: dynamic
          target-platform: linux/s390x
          agent-download-key: ((qa-instana-agent-key))
        params:
          # For brevity, I am omitting env vars like "FLAVOR" and "COMMIT_SHA" that used to be passed to codebuild. Those should
          # be appended here.

      # I am also omitting the `put` step because I don't want to push images from this example. The task outputs `image/image.tar`.
      # that output can be used to push the image like is done in this example:
      # https://github.ibm.com/instana/delivery-infra/blob/main/ci/concourse-examples/docker-build-test-push/pipeline.yml#L60-L62

  - name: ppc64le-build  # just to demo building for more than one target architecture in the same pipeline.
    max_in_flight: 1
    public: true
    plan:
      - get: instana-agent-docker-git
        trigger: true
      - task: build-ppcle64-dynamic
        privileged: true
        file: instana-agent-docker-git/ci/build-any-arch-docker-image-task.yml
        input_mapping:
          source: instana-agent-docker-git
        vars:
          docker-context: dynamic
          target-platform: linux/ppc64le
          agent-download-key: ((qa-instana-agent-key))